try:

    print(x)

except:

    print("erro")